server:
  port: 8030

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
#  boot:
#    admin:
#      client:
#        enabled: false

  sleuth:
    sampler:
      probability: 1.0
    messaging:
      kafka:
        enabled: true

#eureka:
#  client:
#    enabled: false


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full

info:
  app:
    name: \${spring.application.name}
    version: ${version}