apiVersion: v1
kind: Service
metadata:
  name: configuration-server-service
spec:
  selector:
    app: configuration-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
    type: NodePort